version: '3.6'
services:
  hop:
    image: redesblock/hop
    restart: always
    volumes:
      - db_data:/home/hop/.hop
    environment:
      HOP_PASSWORD: "123456"
      HOP_DEBUG_API_ENABLE: "true"
      HOP_MAINNET: "false"
      HOP_NETWORK_ID: 97
      HOP_FULL_NODE: "true"
      HOP_SWAP_ENDPOINT: 127.0.0.1:8575
      # HOP_SWAP_ENDPOINT: "https://data-seed-prebsc-1-s1.binance.org:8545"
      HOP_NAT_ADDR: 127.0.0.1:1634
      HOP_CORS_ALLOWED_ORIGINS: "*"
    command:
      start
    ports:
      - 1633:1633
      - 1634:1634
      - 1635:1635
volumes:
  db_data: